name = "hugo-theme-walden"
license = "MIT"
licenselink = "https://github.com/homecat805/hugo-theme-walden/blob/main/LICENSE"
description = "Walden is a simple-structured, easy-to-use Hugo theme for personal websites."

# The home page of the theme, where the source can be found.
homepage = "https://github.com/homecat805/hugo-theme-walden"

# If you have a running demo of the theme.
demosite = "https://walden.genway.com.cn/"

tags = ["Blog","Personal","Responsive","Multilingual"]
features = ["responsive", "thumbnail","headline","mulitlingual"]

# If the theme has multiple authors
# authors = [
#   {name = "Name of author", homepage = "Website of author"},
#   {name = "Name of author", homepage = "Website of author"}
# ]

# If the theme has a single author
[author]
    name = "Homecat"
    homepage = "https://genway.com.cn/"

# If porting an existing theme
# [original]
#    author = "Name of original author"
#    homepage = "His/Her website"
#    repo = "Link to source code of original theme"